services:
  - type: web
    name: medusa-server
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 9000
      - key: DATABASE_TYPE
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: medusa-postgres
          property: connectionString
      - key: STORE_CORS
        value: https://baytul-jawaher-storefront.onrender.com
      - key: ADMIN_CORS
        value: https://baytul-jawaher-store-admin.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: REDIS_URL
        value: ""
